name: Auto Number Markdown Table

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  auto-number:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run numbering script
        run: python scripts/auto_number.py

      - name: Run UTM parameters script
        run: python scripts/add_utm.py

      - name: Run JSON generation script
        run: python scripts/generate_json.py

      - name: Check for changes
        id: git-check
        run: |
          git add README.md launchdb.json
          git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and Push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: auto-number table and update launchdb.json"
          git push
